feat: add newspapertitle block for hetarchief
viaacode/react-admin-core-module pull request #248
Opened 2024-05-17 08:47 UTC by RobbeBierebeeck

2024-05-17 13:23 UTC, bertyhell requested changes

2024-05-17 13:23 UTC, bertyhell commented on ui/all-translations-het-archief.sql
These sql entries only output NL translations
but they should output both NL and EN translations
can you check that you have the latest admin-core version merged into this branch and run translations extract hetarchief script again?

2024-05-17 13:23 UTC, bertyhell commented on ui/src/react-admin/modules/content-page/components/blocks/BlockOverviewNewspaperTitles/hooks/useIeObjectsNewspaperTitles.ts
> +			enabled: true,
Since this data will never change, we can set a cache time in the client of 1 hour
```suggestion
			enabled: true,
			stateTime: 3600000
```

2024-05-21 18:44 UTC, RobbeBierebeeck commented on ui/all-translations-het-archief.sql
The Branch is up-to-date with the feature/ARC-2145--add-newspaper-block. I have tried running the translations:extract:hetarchief script in the UI repo again. But this reproduces the current result.

2024-05-23 12:21 UTC, merged